package com.studentplanner.model;

import java.math.BigDecimal;
import java.time.LocalDate;

/*
 Model class representing one row in the 'tasks' table.
 Each Task belongs to exactly one Subject (foreign key: subject_id).
 Note: BigDecimal is used for marks_weightage (DECIMAL(5,2) in the DB)
 because float/double would introduce rounding errors.
 */
public class Task {

    // ---------- Attributes ----------
    private int taskId;
    private int subjectId;
    private String title;
    private String description;
    private TaskType taskType;
    private LocalDate dueDate;
    private Priority priority;
    private TaskStatus status;
    private BigDecimal marksWeightage;   // may be null

    // ---------- Constructors ----------

    public Task() {
    }

    /* Constructor for inserting a NEW task where taskId is generated by MySQL. */
    public Task(int subjectId, String title, String description,
                TaskType taskType, LocalDate dueDate,
                Priority priority, TaskStatus status, BigDecimal marksWeightage) {
        this.subjectId = subjectId;
        this.title = title;
        this.description = description;
        this.taskType = taskType;
        this.dueDate = dueDate;
        this.priority = priority;
        this.status = status;
        this.marksWeightage = marksWeightage;
    }

    /* Full constructor that is used when LOADING an existing task from the DB. */
    public Task(int taskId, int subjectId, String title, String description,
                TaskType taskType, LocalDate dueDate,
                Priority priority, TaskStatus status, BigDecimal marksWeightage) {
        this.taskId = taskId;
        this.subjectId = subjectId;
        this.title = title;
        this.description = description;
        this.taskType = taskType;
        this.dueDate = dueDate;
        this.priority = priority;
        this.status = status;
        this.marksWeightage = marksWeightage;
    }

    // ---------- Getters & Setters ----------
    public int getTaskId() { return taskId; }
    public void setTaskId(int taskId) { this.taskId = taskId; }

    public int getSubjectId() { return subjectId; }
    public void setSubjectId(int subjectId) { this.subjectId = subjectId; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public TaskType getTaskType() { return taskType; }
    public void setTaskType(TaskType taskType) { this.taskType = taskType; }

    public LocalDate getDueDate() { return dueDate; }
    public void setDueDate(LocalDate dueDate) { this.dueDate = dueDate; }

    public Priority getPriority() { return priority; }
    public void setPriority(Priority priority) { this.priority = priority; }

    public TaskStatus getStatus() { return status; }
    public void setStatus(TaskStatus status) { this.status = status; }

    public BigDecimal getMarksWeightage() { return marksWeightage; }
    public void setMarksWeightage(BigDecimal marksWeightage) { this.marksWeightage = marksWeightage; }

    // ---------- Behavior ----------

    /*
     Returns true if this task is past its due date AND not yet completed.
     */
    public boolean isOverdue() {
        if (status == TaskStatus.COMPLETED) return false;
        if (dueDate == null) return false;
        return dueDate.isBefore(LocalDate.now());
    }

    @Override
    public String toString() {
        return title + " (due " + dueDate + ")";
    }
}